version : '1'
services:
  db:
    image: mysql
    hostname: localhost
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=bank
      - MYSQL_ROOT_PASSWORD=admin

  rabbitmq:
    image : rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_PASS=guest"
      - "RABBITMQ_DEFAULT_USER=guest"